#!/usr/bin/env python3
"""Generate the reviewable V20 RTL/TBs from the frozen V18A source.

V20 is intentionally a narrow, auditable delta.  The generator requires every
expected V18A pattern exactly once, so an upstream source change fails loudly
instead of silently producing a different circuit.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PACKAGE_ROOT.parent
V18_ROOT = REPO_ROOT / "far_pfdw_v19/reference_v18a"
V19_TB_ROOT = REPO_ROOT / "far_pfdw_v19/tb"
RTL_ROOT = PACKAGE_ROOT / "rtl"
TB_ROOT = PACKAGE_ROOT / "tb"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new)


def replace_count(text: str, old: str, new: str, count: int, label: str) -> str:
    actual = text.count(old)
    if actual != count:
        raise RuntimeError(f"{label}: expected {count} matches, found {actual}")
    return text.replace(old, new)


def generate_engine() -> str:
    text = (V18_ROOT / "pfdw_pipe49_booth_engine_v18a.sv").read_text()
    text = text.replace("pfdw_booth_mul_v18a", "pfdw_booth_mul_v20_w5")
    text = text.replace(
        "pfdw_pipe49_booth_engine_v18a",
        "pfdw_pipe49_booth_engine_v20_w5",
    )
    text = replace_once(
        text,
        '`timescale 1ps/1ps\n',
        '`timescale 1ps/1ps\n\n// AUTO-GENERATED by far_pfdw_v20/scripts/generate_rtl.py.\n'
        '// Frozen source: far_pfdw_v19/reference_v18a.\n'
        '// V20: shared signed W5 weights; common post-MAC scale = 2^3.\n',
        "engine banner",
    )
    text = replace_once(
        text,
        "    logic signed [ACCW-1:0] pp_core [0:NG-1];",
        "    // V20 lane BW is 5..9, therefore NG is 3..5.  Keep five slots\n"
        "    // and tie unused rows to zero so BW=5 never indexes past NG-1.\n"
        "    logic signed [ACCW-1:0] pp_core [0:4];",
        "fixed Booth row bank",
    )
    text = text.replace(
        "// No approximation, quantization, '*' operator, or generic divider is used.",
        "// This multiplier is exact for its W5 operand; quantization is upstream.",
    )
    text = text.replace(
        "//   raw kernel / FC weight  : -128 .. 127 (8-bit signed)",
        "//   quantized kernel/weight : -16 .. 15 (5-bit signed)",
    )
    text = text.replace(
        "//   G horizontal : 10 bits (9 bits for G2; unified by sign extension)\n"
        "    //   G vertical   : 12 bits",
        "//   G horizontal : 7 bits (6 bits for G2; unified by sign extension)\n"
        "    //   G vertical   : 9 bits",
    )
    text = text.replace("p0_b[0..47] : 8-bit weight storage", "p0_b[0..47] : 5-bit weight storage")
    text = text.replace(
        "// These widths are exact for this design; unlike approximate quantization,\n"
        "    // no numerical information used by V3 is discarded.",
        "// These transform widths are exact for the already-quantized W5 operand;\n"
        "    // no additional truncation is introduced inside the engine.",
    )
    text = replace_once(
        text,
        "        corr_vec = '0;\n\n        for (i = 0; i < NG; i = i + 1) begin",
        "        corr_vec = '0;\n"
        "        for (i = 0; i < 5; i = i + 1)\n"
        "            pp_core[i] = '0;\n\n"
        "        for (i = 0; i < NG; i = i + 1) begin",
        "Booth row initialization",
    )
    old_sum = """    always_comb begin
        s01 = pp_core[0] + pp_core[1];
        s23 = pp_core[2] + pp_core[3];
        s45 = '0;

        if (NG == 4) begin
            row_sum = s01 + s23;
        end else if (NG == 5) begin
            row_sum = (s01 + s23) + pp_core[4];
        end else begin
            // V18A maximum BW=12 -> NG=6.
            s45 = pp_core[4] + pp_core[5];
            row_sum = (s01 + s23) + s45;
        end
"""
    new_sum = """    always_comb begin
        // V20 has three to five Booth rows.  Unused fixed slots are zero,
        // keeping the tree legal and balanced for every lane BW.
        s01 = pp_core[0] + pp_core[1];
        s23 = pp_core[2] + pp_core[3];
        s45 = pp_core[4];
        row_sum = (s01 + s23) + s45;
"""
    text = replace_once(text, old_sum, new_sum, "V20 Booth row reduction")

    replacements = (
        ("input  logic signed [7:0]  conv_kernel", "input  logic signed [4:0]  conv_kernel"),
        ("input  logic signed [7:0]  fc_b", "input  logic signed [4:0]  fc_b"),
        ("function automatic logic signed [9:0] g3_h8(", "function automatic logic signed [6:0] g3_h5("),
        ("input logic signed [7:0] x0,\n        input logic signed [7:0] x1,\n        input logic signed [7:0] x2,", "input logic signed [4:0] x0,\n        input logic signed [4:0] x1,\n        input logic signed [4:0] x2,"),
        ("logic signed [9:0] a0, a1, a2;", "logic signed [6:0] a0, a1, a2;"),
        ("a0 = {{2{x0[7]}},x0}; a1 = {{2{x1[7]}},x1}; a2 = {{2{x2[7]}},x2};", "a0 = {{2{x0[4]}},x0}; a1 = {{2{x1[4]}},x1}; a2 = {{2{x2[4]}},x2};"),
        ("g3_h8 =", "g3_h5 ="),
        ("function automatic logic signed [8:0] g2_h8(", "function automatic logic signed [5:0] g2_h5("),
        ("input logic signed [7:0] x0,\n        input logic signed [7:0] x1,", "input logic signed [4:0] x0,\n        input logic signed [4:0] x1,"),
        ("logic signed [8:0] a0, a1;", "logic signed [5:0] a0, a1;"),
        ("a0 = {x0[7],x0}; a1 = {x1[7],x1};", "a0 = {x0[4],x0}; a1 = {x1[4],x1};"),
        ("g2_h8 =", "g2_h5 ="),
        ("function automatic logic signed [9:0] g2_h8_sext10(", "function automatic logic signed [6:0] g2_h5_sext7("),
        ("logic signed [8:0] t;", "logic signed [5:0] t;"),
        ("t = g2_h8(x0,x1,o);", "t = g2_h5(x0,x1,o);"),
        ("g2_h8_sext10 = {t[8],t};", "g2_h5_sext7 = {t[5],t};"),
        ("function automatic logic signed [11:0] g3_v10(", "function automatic logic signed [8:0] g3_v7("),
        ("input logic signed [9:0] x0,\n        input logic signed [9:0] x1,\n        input logic signed [9:0] x2,", "input logic signed [6:0] x0,\n        input logic signed [6:0] x1,\n        input logic signed [6:0] x2,"),
        ("logic signed [11:0] a0, a1, a2;", "logic signed [8:0] a0, a1, a2;"),
        ("a0 = {{2{x0[9]}},x0}; a1 = {{2{x1[9]}},x1}; a2 = {{2{x2[9]}},x2};", "a0 = {{2{x0[6]}},x0}; a1 = {{2{x1[6]}},x1}; a2 = {{2{x2[6]}},x2};"),
        ("g3_v10 =", "g3_v7 ="),
        ("function automatic logic signed [11:0] g2_v10(", "function automatic logic signed [8:0] g2_v7("),
        ("input logic signed [9:0] x0,\n        input logic signed [9:0] x1,", "input logic signed [6:0] x0,\n        input logic signed [6:0] x1,"),
        ("logic signed [11:0] a0, a1;", "logic signed [8:0] a0, a1;"),
        ("a0 = {{2{x0[9]}},x0}; a1 = {{2{x1[9]}},x1};", "a0 = {{2{x0[6]}},x0}; a1 = {{2{x1[6]}},x1};"),
        ("g2_v10 =", "g2_v7 ="),
        ("logic signed [7:0]  p0_b [0:47];", "logic signed [4:0]  p0_b [0:47];"),
        ("logic signed [9:0]  p1_b [0:47];", "logic signed [6:0]  p1_b [0:47];"),
        ("{{2{p0_b[pf][7]}},p0_b[pf]}", "{{2{p0_b[pf][4]}},p0_b[pf]}"),
        ("g3_h8(", "g3_h5("),
        ("g2_h8_sext10(", "g2_h5_sext7("),
        ("logic signed [11:0] p2_b_comb [0:48];", "logic signed [8:0] p2_b_comb [0:48];"),
        ("p2_b_comb[pi] = 12'sd0;", "p2_b_comb[pi] = 9'sd0;"),
        ("{{2{p1_b[pi][9]}},p1_b[pi]}", "{{2{p1_b[pi][6]}},p1_b[pi]}"),
        ("g3_v10(", "g3_v7("),
        ("g2_v10(", "g2_v7("),
    )
    for index, (old, new) in enumerate(replacements):
        if old not in text:
            raise RuntimeError(f"engine replacement {index} missing: {old!r}")
        text = text.replace(old, new)

    lane_bw_old = """                5,6,9,10:\n                    lane_bw = 12;\n                1,2,4,7,8,11,13,14,20,23,33,34:\n                    lane_bw = 11;\n                0,3,12,15,17,19,21,22,24,26,29,30,32,35,37,38,44:\n                    lane_bw = 10;\n                16,18,25,27,28,31,36,39,41,43,45,47:\n                    lane_bw = 9;\n                default:\n                    lane_bw = 8;"""
    lane_bw_new = """                5,6,9,10:\n                    lane_bw = 9;\n                1,2,4,7,8,11,13,14,20,23,33,34:\n                    lane_bw = 8;\n                0,3,12,15,17,19,21,22,24,26,29,30,32,35,37,38,44:\n                    lane_bw = 7;\n                16,18,25,27,28,31,36,39,41,43,45,47:\n                    lane_bw = 6;\n                default:\n                    lane_bw = 5;"""
    text = replace_once(text, lane_bw_old, lane_bw_new, "lane_bw")

    def shrink_lane_pw(match: re.Match[str]) -> str:
        return f"lane_pw={int(match.group(1)) - 3}"

    text, count = re.subn(r"lane_pw=(2[0-5])", shrink_lane_pw, text)
    if count != 49:
        raise RuntimeError(f"lane_pw: expected 49 values, found {count}")

    return text


def generate_chip() -> str:
    text = (V18_ROOT / "chip_pfdw_fc_v18a.sv").read_text()
    text = text.replace("chip_pfdw_fc_v18a", "chip_pfdw_fc_v20_pow2")
    text = text.replace(
        "pfdw_pipe49_booth_engine_v18a",
        "pfdw_pipe49_booth_engine_v20_w5",
    )
    text = replace_once(
        text,
        '`timescale 1ps/1ps\n',
        '`timescale 1ps/1ps\n\n// AUTO-GENERATED by far_pfdw_v20/scripts/generate_rtl.py.\n'
        '// W5 scale=2^3: Conv1=floor, Conv2=truncate-to-zero, FC=nearest-even.\n',
        "chip banner",
    )

    marker = "    // -------------------------------------------------------------------------\n    // Helpers.\n    // -------------------------------------------------------------------------\n"
    quantizers = r'''    // W5 quantizers.  All use a common 2^3 post-MAC scale.
    function automatic logic signed [4:0] quant_floor5(
        input logic signed [7:0] w
    );
        quant_floor5 = $signed(w) >>> 3;
    endfunction

    function automatic logic signed [4:0] quant_trunc5(
        input logic signed [7:0] w
    );
        logic signed [4:0] base;
        logic increment;
        begin
            base = $signed(w) >>> 3;
            increment = w[7] && (|w[2:0]);
            quant_trunc5 = base + {{4{1'b0}}, increment};
        end
    endfunction

    function automatic logic signed [4:0] quant_even5(
        input logic signed [7:0] w
    );
        logic signed [4:0] base;
        logic remainder_gt_half, remainder_eq_half, increment;
        begin
            base = $signed(w) >>> 3;
            remainder_gt_half = w[2] && (w[1] || w[0]);
            remainder_eq_half = w[2] && !w[1] && !w[0];
            increment = remainder_gt_half || (remainder_eq_half && base[0]);
            if ((base == 5'sd15) && increment)
                quant_even5 = base;
            else
                quant_even5 = base + {{4{1'b0}}, increment};
        end
    endfunction

'''
    text = replace_once(text, marker, marker + quantizers, "quantizer insertion")

    text = text.replace(
        "function automatic logic signed [7:0] get_c1_w",
        "function automatic logic signed [4:0] get_c1_w",
    )
    text = text.replace(
        "function automatic logic signed [7:0] get_c2_w",
        "function automatic logic signed [4:0] get_c2_w",
    )
    text = text.replace(
        "function automatic logic signed [7:0] get_fcw",
        "function automatic logic signed [4:0] get_fcw",
    )
    text = re.sub(
        r"get_c1_w = \$signed\((w_1[123]\[\(8\*k\)\+:8\])\);",
        r"get_c1_w = quant_floor5($signed(\1));",
        text,
    )
    text = re.sub(
        r"get_c2_w = \$signed\((w_2[123][123]\[\(8\*k\)\+:8\])\);",
        r"get_c2_w = quant_trunc5($signed(\1));",
        text,
    )
    text = replace_once(
        text,
        "get_fcw = $signed(w_fc[(8*(cls*48+n))+:8]);",
        "get_fcw = quant_even5($signed(w_fc[(8*(cls*48+n))+:8]));",
        "FC quantizer",
    )
    if text.count("quant_floor5($signed(w_1") != 3:
        raise RuntimeError("expected three quantized Conv1 banks")
    if text.count("quant_trunc5($signed(w_2") != 9:
        raise RuntimeError("expected nine quantized Conv2 banks")

    text = replace_count(text, "logic signed [7:0]  req_kernel", "logic signed [4:0]  req_kernel", 1, "req_kernel")
    text = replace_count(text, "logic signed [7:0]  req_fc_b", "logic signed [4:0]  req_fc_b", 1, "req_fc_b")
    text = replace_count(text, "req_kernel[rr][cc] = 8'sd0;", "req_kernel[rr][cc] = 5'sd0;", 1, "req kernel zero")
    text = replace_count(text, "req_fc_b[lane] = 8'sd0;", "req_fc_b[lane] = 5'sd0;", 1, "req fc zero")

    decl = "    logic signed [11:0] rsp_c1q00, rsp_c1q01, rsp_c1q10, rsp_c1q11;\n"
    scaled_decl = (
        decl
        + "    logic signed [31:0] rsp_scaled_y00, rsp_scaled_y01;\n"
        + "    logic signed [31:0] rsp_scaled_y10, rsp_scaled_y11;\n"
        + "    logic signed [39:0] rsp_scaled_fc_sum;\n"
    )
    text = replace_once(text, decl, scaled_decl, "scaled response declarations")
    old_rsp = """        rsp_c1q00 = conv1_q(rsp_y00,get_b1(rsp_oc));
        rsp_c1q01 = conv1_q(rsp_y01,get_b1(rsp_oc));
        rsp_c1q10 = conv1_q(rsp_y10,get_b1(rsp_oc));
        rsp_c1q11 = conv1_q(rsp_y11,get_b1(rsp_oc));

        rsp_eng20_00 = rsp_y00[19:0];
        rsp_eng20_01 = rsp_y01[19:0];
        rsp_eng20_10 = rsp_y10[19:0];
        rsp_eng20_11 = rsp_y11[19:0];"""
    new_rsp = """        rsp_scaled_y00 = $signed(rsp_y00) <<< 3;
        rsp_scaled_y01 = $signed(rsp_y01) <<< 3;
        rsp_scaled_y10 = $signed(rsp_y10) <<< 3;
        rsp_scaled_y11 = $signed(rsp_y11) <<< 3;

        rsp_c1q00 = conv1_q(rsp_scaled_y00,get_b1(rsp_oc));
        rsp_c1q01 = conv1_q(rsp_scaled_y01,get_b1(rsp_oc));
        rsp_c1q10 = conv1_q(rsp_scaled_y10,get_b1(rsp_oc));
        rsp_c1q11 = conv1_q(rsp_scaled_y11,get_b1(rsp_oc));

        rsp_eng20_00 = rsp_scaled_y00[19:0];
        rsp_eng20_01 = rsp_scaled_y01[19:0];
        rsp_eng20_10 = rsp_scaled_y10[19:0];
        rsp_eng20_11 = rsp_scaled_y11[19:0];"""
    text = replace_once(text, old_rsp, new_rsp, "conv scale restore")
    text = replace_once(
        text,
        "        fc_sum20   = rsp_fc_sum[19:0];",
        "        rsp_scaled_fc_sum = $signed(rsp_fc_sum) <<< 3;\n"
        "        fc_sum20   = rsp_scaled_fc_sum[19:0];",
        "FC scale restore",
    )
    return text


def generate_wrapper() -> str:
    source = (V18_ROOT / "chip_v18a_top.v").read_text()
    source = source.replace("V18A", "V20 W5 power-of-two")
    source = source.replace("chip_pfdw_fc_v18a", "chip_pfdw_fc_v20_pow2")
    source = source.replace("u_v18a", "u_v20")
    return source


def generate_tb(source_name: str, top_old: str, top_new: str) -> str:
    text = (V19_TB_ROOT / source_name).read_text()
    text = text.replace(top_old, top_new)
    text = text.replace("chip_pfdw_fc_v19_far", "chip_pfdw_fc_v20_pow2")
    text = text.replace("PFDW V19 FAR", "PFDW V20 W5")
    text = text.replace("PFDW FAR", "PFDW V20 W5")
    text = text.replace("V18A vs V19 FAR", "V18A vs V20 W5")
    text = text.replace("CYCLE COMPARE FAR", "CYCLE COMPARE V20")
    text = text.replace("FAR is decision-identical to V18A for all 1000 images.", "V20 accuracy gate passed.")
    text = text.replace("All 1000 classification decisions are identical.", "V20 accuracy gate passed.")
    if "vs_" in top_new:
        text = replace_once(
            text,
            "    integer mismatch_count;",
            "    integer mismatch_count;\n    integer xz_count;",
            f"{source_name}: X/Z declaration",
        )
        text = replace_once(
            text,
            "        mismatch_count   = 0;",
            "        mismatch_count   = 0;\n        xz_count         = 0;",
            f"{source_name}: X/Z initialization",
        )
        text = replace_once(
            text,
            "            if (base_dec_latched == expected[3:0])",
            "            if ($isunknown(base_dec_latched) ||\n"
            "                $isunknown(pfdw_dec_latched)) begin\n"
            "                xz_count = xz_count + 1;\n"
            "                $display(\"[X/Z] image=%0d baseline=%b pfdw=%b\",\n"
            "                         sample_idx, base_dec_latched, pfdw_dec_latched);\n"
            "            end\n\n"
            "            if (base_dec_latched == expected[3:0])",
            f"{source_name}: X/Z sampling",
        )
        text = replace_once(
            text,
            '        $display(" Decision mismatch: %0d / 1000", mismatch_count);',
            '        $display(" Decision mismatch: %0d / 1000", mismatch_count);\n'
            '        $display(" X/Z decisions    : %0d", xz_count);',
            f"{source_name}: X/Z summary",
        )
    pattern = re.compile(
        r"        if \(match_count == 1000\)\n"
        r"            \$display\(\" RESULT: PASS - .*?\"\);\n"
        r"        else\n"
        r"            \$display\(\" RESULT: CHECK - .*?\"\);"
    )
    condition = "(baseline_correct == 970) && (pfdw_correct >= 970) && (xz_count == 0)"
    if "cycle" in source_name:
        condition += " && (pfdw_cycles_sum <= base_cycles_sum)"
        pass_message = "baseline, V20 accuracy, X/Z and cycle gates passed"
        fail_message = "baseline, accuracy, X/Z or cycle regression"
    else:
        pass_message = "baseline, V20 accuracy and X/Z gates passed"
        fail_message = "baseline, accuracy or X/Z regression"
    replacement = (
        f"        if ({condition})\n"
        f'            $display(" RESULT: PASS - {pass_message}.");\n'
        '        else\n'
        f'            $fatal(1, "RESULT: FAIL - {fail_message}.");'
    )
    text, count = pattern.subn(replacement, text)
    if "vs_" in top_new and count != 1:
        raise RuntimeError(f"{source_name}: comparison gate count={count}")
    if source_name == "top_tb_far_1000.sv":
        # The V19 standalone TB enforces FAR's (ic,oc) traversal by requiring
        # oc=0,1,2 for a fixed activation key.  V20 is deliberately generated
        # from frozen V18A, whose Conv2 traversal is ic=0,1,2 followed by the
        # next oc.  Keeping the FAR-only monitor would therefore reject the
        # correct V18A/V20 schedule before checking a single image.
        text = replace_once(
            text,
            "    // FAR invariant monitor: every convolution activation group must be\n"
            "    // consumed as oc=0,1,2 with an unchanged layer/pr/pc/ic key.\n"
            "    reg        far_group_open;\n"
            "    reg [13:0] far_group_key;\n"
            "    reg [1:0]  far_last_oc;\n\n",
            "",
            "remove V19 FAR-only monitor declarations",
        )
        text = replace_once(
            text,
            "    always @(posedge clk) begin\n"
            "        if (!rst_n) begin\n"
            "            far_group_open <= 1'b0;\n"
            "            far_group_key  <= 14'd0;\n"
            "            far_last_oc    <= 2'd0;\n"
            "        end else if (dut.req_valid && !dut.req_is_fc) begin\n"
            "            if (dut.req_tag[3:2] == 2'd0) begin\n"
            "                if (far_group_open)\n"
            "                    $fatal(1, \"FAR group restarted before oc=2 completed\");\n"
            "                far_group_open <= 1'b1;\n"
            "                far_group_key  <= {dut.req_tag[15:4],dut.req_tag[1:0]};\n"
            "                far_last_oc    <= 2'd0;\n"
            "            end else begin\n"
            "                if (!far_group_open ||\n"
            "                    ({dut.req_tag[15:4],dut.req_tag[1:0]} != far_group_key) ||\n"
            "                    (dut.req_tag[3:2] != (far_last_oc + 1'b1)))\n"
            "                    $fatal(1, \"FAR activation fan-out order violation\");\n"
            "                far_last_oc <= dut.req_tag[3:2];\n"
            "                if (dut.req_tag[3:2] == 2'd2)\n"
            "                    far_group_open <= 1'b0;\n"
            "            end\n"
            "        end\n"
            "    end\n\n",
            "",
            "remove V19 FAR-only monitor logic",
        )
        text = replace_once(
            text,
            "    integer fail_count;",
            "    integer fail_count;\n    integer xz_count;",
            "standalone X/Z declaration",
        )
        text = replace_once(
            text,
            "        fail_count = 0;",
            "        fail_count = 0;\n        xz_count   = 0;",
            "standalone X/Z initialization",
        )
        text = replace_once(
            text,
            "            expected = sample_idx % 10;\n            if (decision == expected[3:0]) begin",
            "            expected = sample_idx % 10;\n"
            "            if ($isunknown(decision)) begin\n"
            "                xz_count = xz_count + 1;\n"
            "                $display(\"[X/Z] image=%0d decision=%b\", sample_idx, decision);\n"
            "            end\n"
            "            if (decision == expected[3:0]) begin",
            "standalone X/Z sampling",
        )
        text = replace_once(
            text,
            '        $display(" Fail    : %0d / 1000", fail_count);',
            '        $display(" Fail    : %0d / 1000", fail_count);\n'
            '        $display(" X/Z     : %0d", xz_count);',
            "standalone X/Z summary",
        )
        text = replace_once(
            text,
            "        #20 $finish;",
            "        if ((accuracy < 970) || (xz_count != 0))\n"
            "            $fatal(1, \"RESULT: FAIL - V20 accuracy or X/Z gate failed.\");\n"
            "        else\n"
            "            $display(\"RESULT: PASS - V20 accuracy and X/Z gates passed.\");\n"
            "        #20 $finish;",
            "standalone accuracy gate",
        )
    timeout_pattern = re.compile(
        r'        \$display\("(\[[^\"]+\] TIMEOUT at %0t ps)", \$time\);\n'
        r"        \$finish;"
    )
    text, timeout_count = timeout_pattern.subn(
        r'        $fatal(1, "\1", $time);', text
    )
    if timeout_count != 1:
        raise RuntimeError(f"{source_name}: timeout gate count={timeout_count}")
    return text


def generate_gate_tb() -> str:
    text = (V19_TB_ROOT / "top_tb_gate_far_1000.sv").read_text()
    text = text.replace("top_tb_gate_far_1000", "top_tb_gate_v20_1000")
    text = text.replace("PFDW V19 FAR", "PFDW V20 W5")
    text = text.replace("[PFDW V19 FAR 1000]", "[PFDW V20 W5 GATE 1000]")
    text = text.replace(
        "1000-image post-synthesis netlist testbench for PFDW V19 FAR.",
        "1000-image zero-delay post-route netlist testbench for PFDW V20 W5.",
    )
    text = replace_once(
        text,
        "    integer fail_count;",
        "    integer fail_count;\n    integer xz_count;",
        "gate X/Z declaration",
    )
    text = replace_once(
        text,
        "        fail_count = 0;",
        "        fail_count = 0;\n        xz_count   = 0;",
        "gate X/Z initialization",
    )
    text = replace_once(
        text,
        "            expected = sample_idx % 10;\n            if (decision == expected[3:0]) begin",
        "            expected = sample_idx % 10;\n"
        "            if ($isunknown(decision)) begin\n"
        "                xz_count = xz_count + 1;\n"
        "                $display(\"[X/Z] image=%0d decision=%b\", sample_idx, decision);\n"
        "            end\n"
        "            if (decision == expected[3:0]) begin",
        "gate X/Z sampling",
    )
    text = replace_once(
        text,
        '        $display(" Fail    : %0d / 1000", fail_count);',
        '        $display(" Fail    : %0d / 1000", fail_count);\n'
        '        $display(" X/Z     : %0d", xz_count);',
        "gate X/Z summary",
    )
    text = replace_once(
        text,
        "        #20 $finish;",
        "        if ((accuracy < 970) || (xz_count != 0))\n"
        "            $fatal(1, \"RESULT: FAIL - V20 gate accuracy or X/Z gate failed.\");\n"
        "        else\n"
        "            $display(\"RESULT: PASS - V20 gate accuracy and X/Z gates passed.\");\n"
        "        #20 $finish;",
        "gate accuracy gate",
    )
    text, timeout_count = re.subn(
        r'        \$display\("(\[[^\"]+\] TIMEOUT at %0t ps)", \$time\);\n'
        r"        \$finish;",
        r'        $fatal(1, "\1", $time);',
        text,
    )
    if timeout_count != 1:
        raise RuntimeError(f"gate TB: timeout gate count={timeout_count}")
    return text


def outputs() -> dict[Path, str]:
    return {
        RTL_ROOT / "pfdw_pipe49_booth_engine_v20_w5.sv": generate_engine(),
        RTL_ROOT / "chip_pfdw_fc_v20_pow2.sv": generate_chip(),
        RTL_ROOT / "chip_v20_pow2_top.v": generate_wrapper(),
        TB_ROOT / "top_tb_v20_1000.sv": generate_tb(
            "top_tb_far_1000.sv", "top_tb_far_1000", "top_tb_v20_1000"
        ),
        TB_ROOT / "top_tb_v20_vs_v18a_1000.sv": generate_tb(
            "top_tb_far_vs_v18a_1000.sv",
            "top_tb_far_vs_v18a_1000",
            "top_tb_v20_vs_v18a_1000",
        ),
        TB_ROOT / "top_tb_cycle_v20_vs_v18a.sv": generate_tb(
            "top_tb_cycle_far_vs_v18a.sv",
            "top_tb_cycle_far_vs_v18a",
            "top_tb_cycle_v20_vs_v18a",
        ),
        TB_ROOT / "top_tb_v20_vs_baseline_1000.sv": generate_tb(
            "top_tb_far_vs_baseline_1000.sv",
            "top_tb_far_vs_baseline_1000",
            "top_tb_v20_vs_baseline_1000",
        ),
        TB_ROOT / "top_tb_cycle_v20_vs_baseline.sv": generate_tb(
            "top_tb_cycle_far_vs_baseline.sv",
            "top_tb_cycle_far_vs_baseline",
            "top_tb_cycle_v20_vs_baseline",
        ),
        TB_ROOT / "top_tb_gate_v20_1000.sv": generate_gate_tb(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(str(path.relative_to(REPO_ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(path.relative_to(REPO_ROOT))
    if stale:
        print("ERROR: generated files are missing or stale:")
        for path in stale:
            print(f"  - {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
